# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/HP/OneDrive/桌面/stu/计组/组成与结构实验5/cache实验基础代码/cache_lab_v0.05/soc_axi_lite_loongson/rtl/xilinx_ip/axi_clock_converter/axi_clock_converter.xci
# IP: The module: 'axi_clock_converter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/HP/OneDrive/桌面/stu/计组/组成与结构实验5/cache实验基础代码/cache_lab_v0.05/soc_axi_lite_loongson/rtl/xilinx_ip/axi_clock_converter/axi_clock_converter_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_clock_converter'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/HP/OneDrive/桌面/stu/计组/组成与结构实验5/cache实验基础代码/cache_lab_v0.05/soc_axi_lite_loongson/rtl/xilinx_ip/axi_clock_converter/axi_clock_converter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_clock_converter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/HP/OneDrive/桌面/stu/计组/组成与结构实验5/cache实验基础代码/cache_lab_v0.05/soc_axi_lite_loongson/rtl/xilinx_ip/axi_clock_converter/axi_clock_converter.xci
# IP: The module: 'axi_clock_converter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/HP/OneDrive/桌面/stu/计组/组成与结构实验5/cache实验基础代码/cache_lab_v0.05/soc_axi_lite_loongson/rtl/xilinx_ip/axi_clock_converter/axi_clock_converter_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_clock_converter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/HP/OneDrive/桌面/stu/计组/组成与结构实验5/cache实验基础代码/cache_lab_v0.05/soc_axi_lite_loongson/rtl/xilinx_ip/axi_clock_converter/axi_clock_converter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_clock_converter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
